name: Code Review

on:
  push:
    branches-ignore:
      - master
jobs:
  code-review:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npm ci
      - run: npm run lint
