name: E2E Runner
on: 
  push:
    branches: [ "master" ]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Ensure the token has write permissions
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Use Cypress env
        uses: cypress-io/github-action@v6
      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos
      - name: Merge test results into one
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate
      - name: List files in public directory
        run: ls -la public
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'Fahdil Ahady Hazain'
          user_email: 'hazain.ahady@gmail.com'
